name: Running Test Suite on Pushes

# We run the test suite on every push
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python Version
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        
    - name: Install dependencies
    # Note that miniconda is installed by default in environments
      run: | 
        conda env update -f linux_environment.yml
        source activate datascience
        python3 setup.py install
        
    - name: Run Tests
      run: python3 setup.py test
