name: Running Test Suite on Pushes

# We run the test suite on every push
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Note that miniconda is installed by default in environments
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: datascience
        environment-file: linux_environment.yml
        python-version: 3.6
        auto-activate-base: true
        
    - name: Setup python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-tests.txt
        make install
        
    - name: Run Tests
      run: make test

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
