name: Running Test Suite on Pushes

# We run the test suite on every push
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Note that miniconda is installed by default in environments
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: datascience
        environment-file: linux_environment.yml
        python-version: 3.6
        auto-activate-base: true
        
    # TODO: Because we are testing, installing some of these requirements
    # manually. Will fix this when it works. 
    - name: Setup python requirements
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install coverage
        pip install coveralls
        pip install bokeh
        
    - name: Run Tests
      run: python3 setup.py test
